name: ReasonWL
version: 2.0
api: 1.12.0
main: reasonWL\ReasonWL
author: CreeperFace
description: plugin for set custom reason for whitelist

commands:
  rwl:
    permission: rwl.command.rwl
    aliases: [reasonwl]
    description: "base rwl command"

                